
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;

namespace BusinessLayer
{
	public class tblBlock : _tblBlock
	{
		public tblBlock()
		{
		
		}


        public DataTable LoadGridData(string strColumnName, string strColumnValue,bool IsSuperAdmin)
        {
            strColumnValue = strColumnValue.Replace("'", "");

            string StrQuery = "select appBlockId, appBlockName, appIsShowContent from tblBlock where 1=1 ";

            if (!string.IsNullOrEmpty(strColumnValue) & strColumnName != "0")
            {
                StrQuery += " and " + strColumnName + " LIKE '%" + strColumnValue + "%'";
            }
            if (!IsSuperAdmin)
            {
                StrQuery += " and appIsShowContent=1 ";
            }
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public DataTable GetBlockByControlId()
        {
            string StrQuery = "select tblBlock.appBlockId, appControlId, appIsShowContent, tblBlock.appContent, appMenuTypeId from tblBlock left join tblMenuType on tblBlock.appBlockId = tblMenuType.appBlockId and tblMenuType.appIsActive = 'true' ";

            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

       

	}
}
