
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
namespace BusinessLayer
{
    public class tblMenuType : _tblMenuType
    {
        public tblMenuType()
        {

        }
        public DataTable LoadGridData(string strColumnName, string strColumnValue)
        {
            strColumnValue = strColumnValue.Replace("'", "");

            string StrQuery = "select appMenuTypeId, appMenuTypeName, appNoOfLevel, appIsActive, (select count(*) from tblMenuItem where appMenuTypeId = main.appMenuTypeId and appParentId = 0) as appChildCount ";
            StrQuery += " from tblMenuType as main ";

            if (strColumnValue != "" && strColumnName != "0")
            {
                StrQuery += "where main." + strColumnName + " LIKE '%" + strColumnValue + "%'";
            }
            else
            {
                StrQuery += "where main." + ColumnNames.AppMenuTypeName + " LIKE '%" + strColumnValue + "%' ";
            }

            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public int GetChildCount(int intId)
        {
            string StrQuery = "";
            DataTable dt = new DataTable();
            StrQuery = "Select count(*) from tblMenuItem where appMenuTypeId = " + intId.ToString();
            base.LoadFromRawSql(StrQuery);
            dt = base.DefaultView.Table;
            return Convert.ToInt32(dt.Rows[0][0]);
        }
        public DataTable  LoadMenuTypes()
        {
            string StrQuery = "select appMenuTypeId, appMenuTypeName from tblMenuType";
            StrQuery += " where appIsActive = 1";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
    }
}
