
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;

namespace BusinessLayer
{
    public class tblPage : _tblPage
    {
        public tblPage()
        {

        }


        string strQry = "";
        public DataTable LoadGridData(string strColumnName, string strColumnValue)
        {
            strColumnValue = strColumnValue.Replace("'", "");

            string StrQuery = "select appPageId, appPageName, appPageHeading, appPageTitle, appIsLink, appLinkURL,appAlias,appIsDefault from tblPage ";

            if (!string.IsNullOrEmpty(strColumnValue) & strColumnName != "")
            {
                StrQuery += "where " + strColumnName + " LIKE '%" + strColumnValue + "%'";
            }
            else if (!string.IsNullOrEmpty(strColumnValue))
            {
                StrQuery += "where " + ColumnNames.AppPageContent + " LIKE '%" + strColumnValue + "%' ";
                StrQuery += "OR " + ColumnNames.AppPageName + " LIKE '%" + strColumnValue + "%' ";
                StrQuery += "OR " + ColumnNames.AppPageTitle + " LIKE '%" + strColumnValue + "%' ";

            }

            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public DataTable LatestAddedPages()
        {
            string StrQuery = "select TOP 5 appPageName, appFullName as appUserName , CONVERT(VARCHAR(10), tblPage.appCreatedDate, 111) as appCreatedOnDate, ";
            StrQuery += " CONVERT(VARCHAR(8), tblPage.appCreatedDate,108) AS appCreatedOnTime from tblPage Left join tblUser on tblUser.appUserId = tblPage.appCreatedBy order by tblPage.appCreatedDate ";

            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public DataTable LoadRoutingDetails(string pageAlias)
        {
            string StrQuery = "select appIsLink, appLinkUrl, tblPageFormat.appPageName from tblPage left join tblPageFormat on tblPage.appPageFormatID = tblPageFormat.appPageFormatId";
            StrQuery += " where tblPage.appAlias = '" + pageAlias + "'";

            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public void ResetDefaultPage()
        {
            strQry = "Update tblPage set appIsDefault='False'";
            base.LoadFromRawSql(strQry);
        }

        public DataTable LoadPageNameAndAlias()
        {
            strQry = "select * from vw_aspnet_PageInfo";
            base.LoadFromRawSql(strQry);
            return base.DefaultView.Table;
        }

        public DataTable GetPageDetailByAlias(string strAlias = "")
        {
            strQry = "select MI.appMenuItemId,MI.appMenuItem,P.appPageID,P.appPageTitle,P.appPageContent,P.appPageHeading,P.appSEOWord,P.appSEODescription,P.appAlias,MI.appParentID,MI.appDisplayOrder ";
            strQry += " from tblPage P left join tblMenuItem MI on P.appPageID=MI.appPageID";

            if (!string.IsNullOrEmpty(strAlias))
            {
                strQry += " where P.AppAlias='" + strAlias + "'";
            }
            base.LoadFromRawSql(strQry);

            DataTable objDT = base.DefaultView.Table.Copy();

            strQry = "select MI.appMenuItemId,MI.appMenuItem,P.appPageID,P.appPageTitle,P.appPageContent,P.appPageHeading,P.appSEOWord,P.appSEODescription,P.appAlias,MI.appParentID ";
            strQry += " from tblPage P right join tblMenuItem MI on P.appPageID=MI.appPageID where P.appPageID is null ";
            base.LoadFromRawSql(strQry);

            objDT.Merge(base.DefaultView.Table);

            return objDT;
        }

    }
}
