
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
namespace BusinessLayer
{
	public class tblSettings : _tblSettings
	{
		public tblSettings()
		{
		
		}

        string strQry = "";
        public DataTable SetLogo()
        {
            strQry = "select * from tblSettings where 1=1 ";
            base.LoadFromRawSql(strQry);
            return base.DefaultView.Table;
        }

	}
}
